export let BungieCredentialType;
(function (BungieCredentialType) {
  BungieCredentialType[(BungieCredentialType['None'] = 0)] = 'None';
  BungieCredentialType[(BungieCredentialType['Xuid'] = 1)] = 'Xuid';
  BungieCredentialType[(BungieCredentialType['Psnid'] = 2)] = 'Psnid';
  BungieCredentialType[(BungieCredentialType['Wlid'] = 3)] = 'Wlid';
  BungieCredentialType[(BungieCredentialType['Fake'] = 4)] = 'Fake';
  BungieCredentialType[(BungieCredentialType['Facebook'] = 5)] = 'Facebook';
  BungieCredentialType[(BungieCredentialType['Google'] = 8)] = 'Google';
  BungieCredentialType[(BungieCredentialType['Windows'] = 9)] = 'Windows';
  BungieCredentialType[(BungieCredentialType['DemonId'] = 10)] = 'DemonId';
  BungieCredentialType[(BungieCredentialType['SteamId'] = 12)] = 'SteamId';
  BungieCredentialType[(BungieCredentialType['BattleNetId'] = 14)] = 'BattleNetId';
  BungieCredentialType[(BungieCredentialType['StadiaId'] = 16)] = 'StadiaId';
  BungieCredentialType[(BungieCredentialType['TwitchId'] = 18)] = 'TwitchId';
  BungieCredentialType[(BungieCredentialType['EgsId'] = 20)] = 'EgsId';
})(BungieCredentialType || (BungieCredentialType = {}));
export let OptInFlags;
(function (OptInFlags) {
  OptInFlags[(OptInFlags['None'] = 0)] = 'None';
  OptInFlags[(OptInFlags['Newsletter'] = 1)] = 'Newsletter';
  OptInFlags[(OptInFlags['System'] = 2)] = 'System';
  OptInFlags[(OptInFlags['Marketing'] = 4)] = 'Marketing';
  OptInFlags[(OptInFlags['UserResearch'] = 8)] = 'UserResearch';
  OptInFlags[(OptInFlags['CustomerService'] = 16)] = 'CustomerService';
  OptInFlags[(OptInFlags['Social'] = 32)] = 'Social';
  OptInFlags[(OptInFlags['PlayTests'] = 64)] = 'PlayTests';
  OptInFlags[(OptInFlags['PlayTestsLocal'] = 128)] = 'PlayTestsLocal';
  OptInFlags[(OptInFlags['Careers'] = 256)] = 'Careers';
})(OptInFlags || (OptInFlags = {}));
